parmalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Flock App"
  description: Flock is a application that allows skaters locate and rate local skate parks.
  font_url: "https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400i,700|Source+Code+Pro:400,700"

  colours:
    background: "--colour-primary"
    accent: "--colour-secondary"
    patterns:
      brand.logos: "--colour-primary"

  rationales:
    typefaces.primary: |
      Akzidenz-Grotesk BQ was selected because of its wide X hight and bold interface.
    typefaces.secondary: |
      Arial regular is my secondary font becuase it creates great contrast with Akzidenz-Grotesk BQ.
    colors.primary: |
      The primary colour was chossen because it is a exciting and attention grabbing colour.
    colors.secondary: |
      The secondary colours contrast the primary.
